
# Configuração do Servidor
server.port=8080

# Configuração do Banco de Dados MySQL
# 1. Instale o MySQL no seu PC
# 2. Crie o banco de dados: CREATE DATABASE regge_db;
# 3. Altere a senha abaixo para a senha do seu usuário root
spring.datasource.url=jdbc:mysql://localhost:3306/regge_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MySQL@1983
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
